AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Interceptor no APIGateway para realizar a autenticação antes de passar do
  proxy
Resources:
  lambdaauth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        Interceptor no APIGateway para realizar a autenticação antes de passar
        do proxy
      MemorySize: 128
      Timeout: 3
      Role: ''
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      VpcConfig:
        SecurityGroupIds:
          - 
        SubnetIds:
          - 
      Layers:
        - ''
